from __future__ import annotations

from pathlib import Path
from typing import Any

from .paths import GENERATED_METRICS_TEX_PATH


_Q2_SOURCE_TEXT = {
    "lm_eval_json": "Q2 metrics source: lm_eval JSON outputs.",
    "report_table_fallback": "Q2 metrics source: fallback to current report table values.",
}


def _fmt(v: float, digits: int = 2) -> str:
    return f"{float(v):.{digits}f}"


def _escape_latex(text: str) -> str:
    return text.replace("_", "\\_")


def render_generated_metrics_tex(q1_payload: dict[str, Any], q2_payload: dict[str, Any]) -> str:
    bart = q1_payload["models"]["BART"]
    gpt2 = q1_payload["models"]["GPT-2"]
    q2 = q2_payload["metrics"]

    source_note = _Q2_SOURCE_TEXT.get(q2_payload.get("source", ""), "Q2 metrics source: unknown.")

    lines = [
        "% Auto-generated by Answer/pipeline/report_macros.py. Do not edit manually.",
        f"\\newcommand{{\\QOneBartDevRaw}}{{{_fmt(bart['dev_raw_em'])}}}",
        f"\\newcommand{{\\QOneBartDevNorm}}{{{_fmt(bart['dev_norm_em'])}}}",
        f"\\newcommand{{\\QOneBartTestRaw}}{{{_fmt(bart['test_raw_em'])}}}",
        f"\\newcommand{{\\QOneBartTestNorm}}{{{_fmt(bart['test_norm_em'])}}}",
        f"\\newcommand{{\\QOneBartTimeSec}}{{{_fmt(bart['training_time_s'])}}}",
        f"\\newcommand{{\\QOneGptDevRaw}}{{{_fmt(gpt2['dev_raw_em'])}}}",
        f"\\newcommand{{\\QOneGptDevNorm}}{{{_fmt(gpt2['dev_norm_em'])}}}",
        f"\\newcommand{{\\QOneGptTestRaw}}{{{_fmt(gpt2['test_raw_em'])}}}",
        f"\\newcommand{{\\QOneGptTestNorm}}{{{_fmt(gpt2['test_norm_em'])}}}",
        f"\\newcommand{{\\QOneGptTimeSec}}{{{_fmt(gpt2['training_time_s'])}}}",
        f"\\newcommand{{\\QTwoPromptStrictBase}}{{{_fmt(float(q2['prompt_level_strict_acc']['base']) * 100.0)}}}",
        f"\\newcommand{{\\QTwoPromptStrictFt}}{{{_fmt(float(q2['prompt_level_strict_acc']['fine_tuned']) * 100.0)}}}",
        f"\\newcommand{{\\QTwoPromptStrictImp}}{{{_fmt(q2['prompt_level_strict_acc']['improvement_pct'])}}}",
        f"\\newcommand{{\\QTwoInstStrictBase}}{{{_fmt(float(q2['inst_level_strict_acc']['base']) * 100.0)}}}",
        f"\\newcommand{{\\QTwoInstStrictFt}}{{{_fmt(float(q2['inst_level_strict_acc']['fine_tuned']) * 100.0)}}}",
        f"\\newcommand{{\\QTwoInstStrictImp}}{{{_fmt(q2['inst_level_strict_acc']['improvement_pct'])}}}",
        f"\\newcommand{{\\QTwoPromptLooseBase}}{{{_fmt(float(q2['prompt_level_loose_acc']['base']) * 100.0)}}}",
        f"\\newcommand{{\\QTwoPromptLooseFt}}{{{_fmt(float(q2['prompt_level_loose_acc']['fine_tuned']) * 100.0)}}}",
        f"\\newcommand{{\\QTwoPromptLooseImp}}{{{_fmt(q2['prompt_level_loose_acc']['improvement_pct'])}}}",
        f"\\newcommand{{\\QTwoInstLooseBase}}{{{_fmt(float(q2['inst_level_loose_acc']['base']) * 100.0)}}}",
        f"\\newcommand{{\\QTwoInstLooseFt}}{{{_fmt(float(q2['inst_level_loose_acc']['fine_tuned']) * 100.0)}}}",
        f"\\newcommand{{\\QTwoInstLooseImp}}{{{_fmt(q2['inst_level_loose_acc']['improvement_pct'])}}}",
        f"\\newcommand{{\\QTwoSourceNote}}{{{_escape_latex(source_note)}}}",
        "",
    ]
    return "\n".join(lines)


def write_generated_metrics_tex(
    q1_payload: dict[str, Any],
    q2_payload: dict[str, Any],
    output_path: Path = GENERATED_METRICS_TEX_PATH,
) -> Path:
    tex = render_generated_metrics_tex(q1_payload, q2_payload)
    output_path.write_text(tex)
    return output_path
